---
# https://taskfile.dev
version: '3'

vars:
  ACTION: create

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  k0s-controller:
    cmds:
      - sudo podman volume create k0s-controller
      - "sudo podman run \
          --detach \
          --name k0s \
          --hostname k0s \
          --privileged \
          --volume k0s-controller:/var/lib/k0s \
          --cgroupns=host \
          --volume /sys/fs/cgroup:/sys/fs/cgroup:rw \
          --publish 6443:6443 \
          docker.io/k0sproject/k0s:latest"
      - "sudo podman exec k0s \
         cat /var/lib/k0s/pki/admin.conf > k0s.kubeconfig.yaml"

  k0s-worker1:
    cmds:
      - sudo podman volume create k0s-worker1
      - "sudo podman run \
          --detach \
          --name k0s-worker1 \
          --hostname k0s-worker1 \
          --privileged \
          --volume k0s-worker1:/var/lib/k0s \
          --volume /sys/fs/cgroup:/sys/fs/cgroup:rw \
          --cgroupns=host \
          --publish 31234:31234 \
          docker.io/k0sproject/k0s:latest \
            k0s worker {{.TOKEN}}"
    vars:
      TOKEN:
        sh: sudo podman exec -t -i k0s k0s token create --role=worker

  apply:
    cmds:
      - "kubectl \
         --kubeconfig=./k0s.kubeconfig.yaml \
         apply -f ./src/kube_manifests/"

  delete:
    cmds:
      - "kubectl \
         --kubeconfig=./k0s.kubeconfig.yaml \
         delete -f ./src/kube_manifests/"

  stop:
    cmds:
      - sudo podman container stop k0s
      - sudo podman container stop k0s-worker1

  remove:
    cmds:
      - sudo podman container rm k0s
      - sudo podman container rm k0s-worker1

  clean:
    deps:
      - stop
      - remove
    cmds:
      - sudo podman volume rm k0s-controller
      - sudo podman volume rm k0s-worker1

  ansible-galaxy:
    desc: 'Install all requirements'
    cmds:
      - "ansible-galaxy collection install \
         --requirements-file collections/requirements.yml \
         --collections-path collections"
      - "ansible-galaxy role install \
         --role-file roles/requirements.yml \
         --roles-path roles"

  ansible-playbook:
    desc: 'Run Ansible-Playbook'
    cmds:
      - "ansible-playbook \
         --extra-vars=ansible_action={{.ACTION}} \
         --ask-become-pass \
         ansible-playbook-k0s-in-podman.yaml"
...
